### ISSUE TITLE
Didn't work. Empty page are displayed

### ISSUE THREAD

**Issue by amorphius** [xinchaobeta/compile-selected-es6#1]
Which path should I add to the PATH? /usr/local/lib/node_modules? Or /usr/local/lib/node_modules/babel/bin/babel-node? Now I have empty page open when trying to compile

**Comment by xinchaobeta** [comment]
The PATH is the directory which contains the executed babel command, you can use  

``` bash
npm bin -g
```

to see the path in you computer.

**Comment by amorphius** [comment]
It shows /usr/local/bin which is already in the PATH, but doesn't work

**Comment by xinchaobeta** [comment]
You can try setting the plugin `envPATH` by
`Preferences > Package Settings > Compile Selected ES6 > Settings - User`

``` json
{
  "envPATH": "THE ACTUAL PATH IN YOUR COMPUTER"
}
```

**Comment by amorphius** [comment]
Now it works, but does not understand decorators. I've set stage to 0, which should work.

**Comment by xinchaobeta** [comment]
Use quotation   mark `"0"` 

``` json
{
  "stage": "0"
}
```

**Comment by xinchaobeta** [comment]
Now I have update the plugin to v0.2.5, which will both support `{"stage": 0}` and `{"stage": "0"}` https://github.com/xinchaobeta/compile-selected-es6/commit/57e0ce746054b124b39f72763510f0796da96870

**Comment by Juribiyan** [comment]
How to make it work on Windows? Here are my User Setings:

```
{
  "envPATH": "C:\\Users\\username\\AppData\\Roaming\\npm"
}
```

The response is empty plus I get a syntax error when trying to save changes in `.sublime-settings` file.

**Comment by xinchaobeta** [comment]
I will no longer support this plugin, because the [Official Babel Plugin](https://packagecontrol.io/packages/Babel) is now perfect enough.
